### ISSUE TITLE
[💡SUG] 您好，请问有没有临时的使用手册？

### ISSUE THREAD

**Issue by wu1hong** [RUCAIBox/RecBole-CDR#32]
各位开发者好，我是从RecBole过来的用户，一些CDR的功能对我来说很香。
我知道该项目仍在初期开发阶段，但是不知道有没有临时的/初步的手册指导一下大致的使用方法。
万分感谢

**Comment by linzihan-backforward** [comment]
您好，RecBole-CDR针对cross-domain场景下基于RecBole的二次开发库，目前主要功能为自动加载和对齐两个数据集，并调用一些已实现的模型进行训练，并在target数据集上进行测试。对于没有实现新模型需求的用户，可以直接在配置文件中设置`source_domain`和`target_domain`两个参数来指定数据集，具体可以参考代码中的(https://github.com/RUCAIBox/RecBole-CDR/tree/main/recbole_cdr/properties/dataset/sample.yaml 文件中的样例。具体支持参数与RecBole一致，会自动对ID相同的User和Item进行对齐，也可以通过设置`user_link_file_path`或`item_link_file_path`来指定对齐方式。目前功能还比较有限，如果您有希望支持的功能或者使用上的疑问可以提出以供我们改进，谢谢！

**Comment by wu1hong** [comment]
好的好的，非常感谢各位开发者！
