### ISSUE TITLE
[🐛BUG] bitgcf.py/transfer_layer function:line 163有误

### ISSUE THREAD

**Issue by WYH-han** [RUCAIBox/RecBole-CDR#34]
![image](https://user-images.githubusercontent.com/35283868/186057359-1b97d6c3-53e0-4aff-856c-17571405919d.png)
应修改为：source_overlap_item_embeddings = (source_item_embeddings_lam[:self.overlapped_num_items] + source_item_embeddings_lap[:self.overlapped_num_items]) / 2

**Comment by Wicknight** [comment]
@WYH-han 抱歉没有及时回复您的问题，非常感谢您指出代码中的错误，我们已经在 #36 中进行了修复。
