### ISSUE TITLE
[💡SUG] 推荐任务问题

### ISSUE THREAD

**Issue by luanxian1** [RUCAIBox/RecBole-CDR#38]
首先感谢你们能开源这样一个强大的库。在你们的代码你们实现的topn任务中，我想请教一下是否可以将topn任务改成高度预测的任务？就更好了

**Comment by Wicknight** [comment]
@luanxian1 您好，非常感谢您对RecBole-CDR的关注和支持！我没有特别明确您问题中“高度预测”这一任务的定义，您指的是否是点击率预估（CTR）任务呢？希望您能详细地说明一下以帮助我们更好地改进

**Comment by luanxian1** [comment]
不好意思，我打错字了，我想问的是评分预测任务

**Comment by Wicknight** [comment]
@您好！目前RecBole-CDR还不支持评分预测任务，我们在后续开发中会考虑这一任务，也欢迎您对我们的代码进行修改并提出PR！

**Comment by Wicknight** [comment]
由于长时间无回复，该issue将被关闭，如后续有任何建议欢迎与我们继续交流！
