### ISSUE TITLE
[🐛BUG] remap过程中的item feature设置

### ISSUE THREAD

**Issue by WYH-han** [RUCAIBox/RecBole-CDR#51]
**描述这个 bug**
<img width="953" alt="image" src="https://user-images.githubusercontent.com/35283868/223041062-3bd1ea36-c716-4bdb-a956-55311213b750.png">

**预期**
将
`self.user_feat[field_name] = self.item_feat[field_name].map(lambda x: map_dict.get(x, x))`
修改为：
`self.item_feat[field_name] = self.item_feat[field_name].map(lambda x: map_dict.get(x, x))`

**Comment by Wicknight** [comment]
@WYH-han 您好！感谢您的建议，我们已经将这个bug修改！
