### ISSUE TITLE
[🐛BUG] BiTGCF模型鲁棒性

### ISSUE THREAD

**Issue by WYH-han** [RUCAIBox/RecBole-CDR#53]
**描述这个 bug**
BiTGCF模型中包含Feature Transfer部分，其中在公式(15)-(16)计算user(item)-related weight factor时，需要考虑多跳后可能出现某些节点的邻居为0，即公式(15)中分母可能为0的情况，则会导致模型训练中出现“nan”。报错如下：
![image](https://user-images.githubusercontent.com/35283868/231623981-55217f69-0eaa-4b38-849e-da5280697283.png)
![image](https://user-images.githubusercontent.com/35283868/231624005-83f1eec2-ce5e-4233-8edf-abef3623576f.png)

**预期**
为了避免“除0”问题，针对项目代码中的user_laplace和item_laplace，即分母，添加一个极小数以避免出现“除0”问题。
<img width="379" alt="image" src="https://user-images.githubusercontent.com/35283868/231623440-b7149f99-3c6b-4885-b115-8b08cdd901f5.png">

**屏幕截图**
![image](https://user-images.githubusercontent.com/35283868/231622643-24e5e769-d799-4769-9c6a-aa4b21ad4795.png)

**Comment by Wicknight** [comment]
@WYH-han 感谢您的提醒，我们已经在 #56 中修复了这个问题！
