### ISSUE TITLE
Ranking Metrics Question

### ISSUE THREAD

**Issue by ajaykv1** [RUCAIBox/RecBole-CDR#55]
Hi, I am trying to calculate the NDCG@10, MRR@10, and HR@10 on my dataset. My dataset is quite small, and some users may not rate up to 10 items in the test set. Usually, we look at the top 10 predictions and check to see if the predictions are in the ground truth for the given user. But, if the user in the test set does not rate that many items, how does RecBole-CDR handle this case?

**Comment by nicksukie** [comment]
I think you can change `topk` to a lower value in your config file.
