### ISSUE TITLE
关于 Bi-TGCF 代码实现的咨询

### ISSUE THREAD

**Issue by Jaccelerator** [RUCAIBox/RecBole-CDR#64]
您好，在 Bi-TGCF 实现中，在类的初始化部分，发现指定这些行为 0（应该是不在 source/target 中的用户？），不知道有没有必要呢？

https://github.com/RUCAIBox/RecBole-CDR/blob/d339918ee5f2fb2d3ef38e874f2e04c01bc19e9d/recbole_cdr/model/cross_domain_recommender/bitgcf.py#L59-L64

因为后面紧跟着又来了个参数初始化：

https://github.com/RUCAIBox/RecBole-CDR/blob/d339918ee5f2fb2d3ef38e874f2e04c01bc19e9d/recbole_cdr/model/cross_domain_recommender/bitgcf.py#L89

**Comment by Wicknight** [comment]
@Jaccelerator 
您好，感谢您对RecBole-CDR的关注，也为迟来的回复向您致歉！这里由于后续的参数初始化，确实会对上文的操作进行覆盖，可以将其删除，感谢您的提醒！
